### ISSUE TITLE
Timestamp conversion does not handle daylight time

### ISSUE THREAD

**Issue by pwoods25443** [freach/udatetime#10]
It looks like `udatetime` does not handle changing utc offset for daylight savings time at different times of year, so the unit tests that use local timezone are failing when run in US Eastern Timezone. 

Here is the problem: https://github.com/freach/udatetime/blob/master/src/rfc3339.c#L74
`udatetime` uses the same UTC offset (in my case -4) for all dates, but `datetime` correctly uses -5 in January and -4 in August

``` console
In[2]: import udatetime
In[3]: from datetime import datetime

In[4]: udatetime.fromtimestamp(1471046400)
Out[4]: datetime.datetime(2016, 8, 12, 20, 0, tzinfo=--4:00)
In[5]: datetime.fromtimestamp(1471046400)
Out[5]: datetime.datetime(2016, 8, 12, 20, 0)

In[6]: udatetime.fromtimestamp(1451606400)
Out[6]: datetime.datetime(2015, 12, 31, 20, 0, tzinfo=--4:00)
In[7]: datetime.fromtimestamp(1451606400)
Out[7]: datetime.datetime(2015, 12, 31, 19, 0)

In[8]: udatetime.fromtimestamp(0)
Out[8]: datetime.datetime(1969, 12, 31, 20, 0, tzinfo=--4:00)
In[9]: datetime.fromtimestamp(0)
Out[9]: datetime.datetime(1969, 12, 31, 19, 0)

```

Recommend changing the unit tests to avoid this problem buy using utcfromtimestamp() in the tests that do not supply a timestamp.  

In future, consider avoiding the problem entirely by always assuming that any datetime that does not come with an explicit timezone offset is UTC and never use the local timezone implicitly.   Since this library is all about high performance for high volume throughput, it seems likely that most use cases will be using UTC anyway.

**Comment by pwoods25443** [comment]
Forgot to mention, I am using python 2.7 on OSX

**Comment by freach** [comment]
I can reproduce it, working on a fix.
