### ISSUE TITLE
Segmentation fault when i run utcnow frequently

### ISSUE THREAD

**Issue by xiewenlongs** [freach/udatetime#12]
I use ipython's timeit to benchmark udatetime like:

>  %timeit -n 1000000 -r 10 udatetime.utcnow()

when i repeat this command 5 times, it block serveral seconds and print :  Segmentation fault (core dumped) 

datetime library is ok

**Comment by freach** [comment]
Can't reproduce on my system. What OS, Python version, iPython version are you using?

**Comment by xiewenlongs** [comment]
Linux distro:    Ubuntu 14.04.2 LTS
python version:  2.7.6
ipython version:  1.2.1

![screen shot 2016-08-30 at 11 43 45](https://cloud.githubusercontent.com/assets/8335907/18075404/0f70b068-6ea7-11e6-97f6-a876854b4206.jpg)

**Comment by freach** [comment]
Sorry can't be reproduced.
