### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by gregers666** [freach/udatetime#18]
Please check using i.e. htop:

#!/usr/bin/python3
# -*- coding:utf8 -*-

import udatetime
while True:
    udatetime.now()

It eats megabytes in seconds. 
I use your library, beacause it's very fast - but this problem was pretty hard to find.

Sincerely
Gregory

**Comment by freach** [comment]
Thanks for your report, I can confirm the issue. Working on fix.

**Comment by freach** [comment]
Just released version 0.0.12 on https://pypi.python.org/pypi/udatetime
