### ISSUE TITLE
Consider moving rfc3339 module under udatetime

### ISSUE THREAD

**Issue by iliastsi** [freach/udatetime#19]
Hi!

The udatetime package installs the rfc3339 module at the top-level, effectively shadowing the [rfc3339](https://pypi.python.org/pypi/rfc3339/) Python package. Do you think it is possible to move the rfc3339 module under udatetime?

**Comment by iliastsi** [comment]
Thanks for considering this. To be honest, I had in mind something like [this](https://sources.debian.net/src/python-udatetime/0.0.12-2/debian/patches/0001-Move-rfc3339-module-under-udatetime.patch/), which moves rfc3339 under udatetime (i.e., `import udatetime.rfc3339`). I see no reason why the udatetime Python package should install both udatetime and urfc3339 modules, and this also is documented as packaging best practices in [PEP 423](https://www.python.org/dev/peps/pep-0423/#use-a-single-name). In the end, of course, it's up to you (as long as it doesn't conflict with other modules).

Please note that the above patch [reverts](https://github.com/freach/udatetime/commit/7ad26a49a982f085b477a3a996f3ec832fde0f63#diff-de39c4b5d957eccfefeae5638d709bd6L259) the fix about out-of-bounds read.

**Comment by freach** [comment]
Thanks for clearing that up. You're right managing under udatetime is much cleaner. I reflected your request in 9e929e76ad47edc1d1289b3a381be3820e012c04 also applied the out-of-bounds read fix in da2b8191aace871d3dc50d408add27904d2b936f.

**Comment by iliastsi** [comment]
Thanks for taking care of this so quickly :-)
