### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by kierun** [freach/udatetime#2]
I tried to install this on CentOS 7 and got this error:

```
; pip install udatetime
Collecting udatetime
  Using cached udatetime-0.0.2.tar.gz
Building wheels for collected packages: udatetime
  Running setup.py bdist_wheel for udatetime ... error
  Complete output from command /home/usr/.virtualenvs/mead/bin/python -u -c "im
port setuptools, tokenize;__file__='/tmp/pip-build-1v_otE/udatetime/setup.py';ex
ec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'
), __file__, 'exec'))" bdist_wheel -d /tmp/tmpxo1peqpip-wheel- --python-tag cp27
:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/udatetime
  copying udatetime/__init__.py -> build/lib.linux-x86_64-2.7/udatetime
  running egg_info
  writing udatetime.egg-info/PKG-INFO
  writing top-level names to udatetime.egg-info/top_level.txt
  writing dependency_links to udatetime.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'udatetime.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'udatetime.egg-info/SOURCES.txt'
  running build_ext
  building 'rfc3339' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -
fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-swit
ches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall
 -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffe
r-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -
fPIC -I/usr/include/python2.7 -c ./src/rfc3339.c -o build/temp.linux-x86_64-2.7/
./src/rfc3339.o -Ofast
  In file included from /usr/include/python2.7/pyconfig.h:6:0,
                   from /usr/include/python2.7/Python.h:8,
                   from ./src/rfc3339.c:8:
  /usr/include/python2.7/pyconfig-64.h:1182:0: warning: "_POSIX_C_SOURCE" redefi
ned [enabled by default]
   #define _POSIX_C_SOURCE 200112L
   ^
  In file included from /usr/include/math.h:27:0,
                   from ./src/rfc3339.c:1:
  /usr/include/features.h:168:0: note: this is the location of the previous defi
nition
   # define _POSIX_C_SOURCE 200809L
   ^
  In file included from /usr/include/python2.7/pyconfig.h:6:0,
                   from /usr/include/python2.7/Python.h:8,
                   from ./src/rfc3339.c:8:
  /usr/include/python2.7/pyconfig-64.h:1204:0: warning: "_XOPEN_SOURCE" redefine
d [enabled by default]
   #define _XOPEN_SOURCE 600
   ^
  In file included from /usr/include/math.h:27:0,
                   from ./src/rfc3339.c:1:
  /usr/include/features.h:170:0: note: this is the location of the previous defi
nition
   # define _XOPEN_SOURCE 700
   ^
  ./src/rfc3339.c: In function ‘_parse_time’:
  ./src/rfc3339.c:250:9: error: ‘for’ loop initial declarations are only allowed
 in C99 mode
           for (unsigned int i = 0; i < 6; i++) {
           ^
  ./src/rfc3339.c:250:9: note: use option -std=c99 or -std=gnu99 to compile your
 code
  error: command 'gcc' failed with exit status 1

```

**Comment by freach** [comment]
Just released version 0.0.3. Please make sure you try again with version 0.0.3. Thanks for reporting!

**Comment by kierun** [comment]
Confirmed it works fine.

```
; pip install --user udatetime
Collecting udatetime
  Downloading udatetime-0.0.3.tar.gz
Installing collected packages: udatetime
  Running setup.py install for udatetime ... done
Successfully installed udatetime-0.0.3
```

Thank you very much!

**Comment by xin7c** [comment]
sudo pip install udatetime
Collecting udatetime
  Using cached udatetime-0.0.8.tar.gz
Building wheels for collected packages: udatetime
  Running setup.py bdist_wheel for udatetime ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-gC0VyA/udatetime/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /tmp/tmp5sWMG1pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/udatetime
  copying udatetime/**init**.py -> build/lib.linux-x86_64-2.7/udatetime
  copying udatetime/_pure.py -> build/lib.linux-x86_64-2.7/udatetime
  running egg_info
  writing udatetime.egg-info/PKG-INFO
  writing top-level names to udatetime.egg-info/top_level.txt
  writing dependency_links to udatetime.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'udatetime.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'udatetime.egg-info/SOURCES.txt'
  running build_ext
  building 'rfc3339' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_PYTHON2=1 -I/usr/local/include/python2.7 -c ./src/rfc3339.c -o build/temp.linux-x86_64-2.7/./src/rfc3339.o -Ofast -std=c99
  cc1: 错误：无效的选项参数‘-Ofast’
  error: command 'gcc' failed with exit status 1

---

  Failed building wheel for udatetime
  Running setup.py clean for udatetime
Failed to build udatetime
Installing collected packages: udatetime
  Running setup.py install for udatetime ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-gC0VyA/udatetime/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-cvC4Eo-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/udatetime
    copying udatetime/**init**.py -> build/lib.linux-x86_64-2.7/udatetime
    copying udatetime/_pure.py -> build/lib.linux-x86_64-2.7/udatetime
    running egg_info
    writing udatetime.egg-info/PKG-INFO
    writing top-level names to udatetime.egg-info/top_level.txt
    writing dependency_links to udatetime.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

```
reading manifest file 'udatetime.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'udatetime.egg-info/SOURCES.txt'
running build_ext
building 'rfc3339' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_PYTHON2=1 -I/usr/local/include/python2.7 -c ./src/rfc3339.c -o build/temp.linux-x86_64-2.7/./src/rfc3339.o -Ofast -std=c99
cc1: 错误：无效的选项参数‘-Ofast’
error: command 'gcc' failed with exit status 1

----------------------------------------
```

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-gC0VyA/udatetime/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-cvC4Eo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-gC0VyA/udatetime/

**Comment by xin7c** [comment]
Help!

**Comment by freach** [comment]
@xin7c please open a new issue and provide your OS information and gcc version.
