### ISSUE TITLE
Timestamp generation

### ISSUE THREAD

**Issue by mkusz** [freach/udatetime#27]
It would be nice to have some faster timestamp generation that one get from pure datetime.timestamp() or time.time(). It can be very useful for any logging, etc. in case of fast application (like load testing using locust.io)

**Comment by freach** [comment]
The `time()` implementation is already using straight C functions to create a timestamp. Depending on your OS it's basically `create Python Float from gettimeofday`. I'm afraid there is nothing to optimize here.
